In [1]:
import numpy as np

# The basics

In [5]:
k=np.arange(15)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
m=k.reshape(3,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
k.shape


(15,)

In [11]:
m.shape

(3, 5)

In [13]:
m.ndim

2

In [17]:
m.dtype.name

'int32'

In [20]:
m.size

15

In [22]:
type(m)

numpy.ndarray

# Array creation

In [27]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [31]:

b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.zeros((3,4))
# argument  is a tuple

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [39]:
np.arange(1,11,2)
# from 1  to 10  by 2
# 11 is exclusive

array([1, 3, 5, 7, 9])

In [40]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
np.linspace(0,20,10)
# 10 elements

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [46]:
from numpy import pi
x = np.linspace(0, 2 * pi, 100)       
# useful to evaluate function at lots of points
f = np.sin(x)

# Basic operations

In [53]:
#Arithmetic operators on arrays apply elementwise
a=np.array([20,30,40,50])
b=np.arange(4)
a-b


array([20, 29, 38, 47])

In [54]:
a**2

array([ 400,  900, 1600, 2500])

In [55]:
a<35

array([ True,  True, False, False])

In [56]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [58]:
A @ B  # matrix product

array([[5, 4],
       [3, 4]])

In [59]:
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

In [62]:
a.sum()

140

In [63]:
a.min()

20

In [64]:
a.max()

50

In [72]:
A=np.arange(12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
A.sum(axis=0)   # sum of each column

array([12, 15, 18, 21])

In [75]:
A.cumsum(axis=1)  #cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Indexing and slicing 

In [77]:
# only for One-dimensional array
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a[2:5]

array([2, 3, 4])

In [81]:
a[2:8:2] #from  a[2] (2) to a[8] (8),exclusive , each 2nd element

array([2, 4, 6])

In [82]:
a[::-1]  # reversed a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [103]:
b=np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
b[2,3]  # row 2  col 3   (start from 0)

11

In [93]:
b[0:3, 1]     # row 0 col 1 ,row 1 col 1 ,row 2 col 1 

array([1, 5, 9])

In [94]:
b[-1]   # the last row. Equivalent to b[-1, :]

array([12, 13, 14, 15])

# Shape manipulation

In [104]:
b.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [105]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
b.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [107]:
b.resize((2,8))
b 
# modifies the array itself 

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [108]:
#If a dimension is given as -1 in a reshaping operation,
#the other dimensions are automatically calculated:
b.reshape(4,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Stacking together different arrays

In [111]:
rg = np.random.default_rng()
a = np.floor(10 * rg.random((2, 2)))
a

array([[8., 1.],
       [6., 1.]])

In [112]:
b = np.floor(10 * rg.random((2, 2)))
b

array([[4., 8.],
       [0., 8.]])

In [113]:
np.vstack((a, b))

array([[8., 1.],
       [6., 1.],
       [4., 8.],
       [0., 8.]])

In [114]:
np.hstack((a, b))

array([[8., 1., 4., 8.],
       [6., 1., 0., 8.]])

# Splitting one array into several smaller ones

In [117]:
a = np.floor(10 * rg.random((4, 12)))
a

array([[3., 4., 4., 6., 2., 7., 1., 6., 5., 8., 3., 8.],
       [4., 5., 2., 2., 7., 3., 1., 1., 4., 8., 5., 7.],
       [3., 9., 4., 3., 9., 8., 3., 0., 1., 5., 8., 2.],
       [6., 2., 3., 7., 2., 7., 5., 5., 7., 5., 0., 7.]])

In [118]:
np.hsplit(a, 3)

[array([[3., 4., 4., 6.],
        [4., 5., 2., 2.],
        [3., 9., 4., 3.],
        [6., 2., 3., 7.]]),
 array([[2., 7., 1., 6.],
        [7., 3., 1., 1.],
        [9., 8., 3., 0.],
        [2., 7., 5., 5.]]),
 array([[5., 8., 3., 8.],
        [4., 8., 5., 7.],
        [1., 5., 8., 2.],
        [7., 5., 0., 7.]])]

In [119]:
np.vsplit(a,4)

[array([[3., 4., 4., 6., 2., 7., 1., 6., 5., 8., 3., 8.]]),
 array([[4., 5., 2., 2., 7., 3., 1., 1., 4., 8., 5., 7.]]),
 array([[3., 9., 4., 3., 9., 8., 3., 0., 1., 5., 8., 2.]]),
 array([[6., 2., 3., 7., 2., 7., 5., 5., 7., 5., 0., 7.]])]

# copy

In [124]:
d=a.copy()
d is a 

False

In [125]:
d

array([[3., 4., 4., 6., 2., 7., 1., 6., 5., 8., 3., 8.],
       [4., 5., 2., 2., 7., 3., 1., 1., 4., 8., 5., 7.],
       [3., 9., 4., 3., 9., 8., 3., 0., 1., 5., 8., 2.],
       [6., 2., 3., 7., 2., 7., 5., 5., 7., 5., 0., 7.]])

In [126]:
a

array([[3., 4., 4., 6., 2., 7., 1., 6., 5., 8., 3., 8.],
       [4., 5., 2., 2., 7., 3., 1., 1., 4., 8., 5., 7.],
       [3., 9., 4., 3., 9., 8., 3., 0., 1., 5., 8., 2.],
       [6., 2., 3., 7., 2., 7., 5., 5., 7., 5., 0., 7.]])

In [127]:
d==a

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True]])

# Indexing with boolean arrays

In [129]:
a = np.arange(12).reshape(3, 4)
a 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
a>4

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [131]:
a[a>4]

array([ 5,  6,  7,  8,  9, 10, 11])